Repository openid/OpenID4VC-HAIP, pull requests merged in 2025-09, with the labels that each got.

#165 Changes to additional SD-JWT VC requirements
  openid4vc-high-assurance-interoperability-profile-1_0.md
Labels: needs-reviews

#254 minor editorial changes
  openid4vc-high-assurance-interoperability-profile-1_0.md
Labels: editorial

#261 Editorial: Combine the two 'Issuer Metdata' sections
  openid4vc-high-assurance-interoperability-profile-1_0.md
Labels: editorial

#252 prohibit self-signed certificates for x509_hash
  openid4vc-high-assurance-interoperability-profile-1_0.md
Labels: discuss

#229 clarify batch issuance requirements
  openid4vc-high-assurance-interoperability-profile-1_0.md
Labels: needs-reviews

#277 Remove requirement that SD-JWT iss is a https url
  openid4vc-high-assurance-interoperability-profile-1_0.md
Labels: has-at-least-3-approvals
