Repository openid/OpenID4VC-HAIP, pull requests merged in 2025-10, with the labels that each got.

#294 remove intent to retain related text
  openid4vc-high-assurance-interoperability-profile-1_0.md
Labels: has-at-least-3-approvals

#280 Add guidance around key sizes
  openid4vc-high-assurance-interoperability-profile-1_0.md
Labels: needs-reviews

#290 Specify image formats for credential issuer metadata
  openid4vc-high-assurance-interoperability-profile-1_0.md
Labels: has-at-least-3-approvals

#296 Tweak security considerations reference to OID4VP/VCI
  openid4vc-high-assurance-interoperability-profile-1_0.md
Labels: editorial

#214 Require use of (most of) FAPI2 with VCI
  openid4vc-high-assurance-interoperability-profile-1_0.md
Labels: has-at-least-3-approvals
